version: "3.8"

services:
  db:
    image: postgres:16
    container_name: pg-sicredi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votacao
    ports:
      - "5432:5432"
    volumes:
      - pgdata_sicredi:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sicredi-api:dev
    container_name: sicredi-api
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/votacao"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9091:9090"   # Prometheus UI
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"   # Grafana UI
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  pgdata_sicredi:
  grafana_storage:
