version: "3.8"

services:
  db:
    image: postgres:16
    container_name: pg-sicredi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votacao
    ports:
      - "5432:5432"
    volumes:
      - pgdata_sicredi:/var/lib/postgresql/data
    command: [
      "postgres",
      "-c", "max_connections=25",
      "-c", "shared_buffers=64MB",
      "-c", "effective_cache_size=256MB",
      "-c", "work_mem=4MB",
      "-c", "maintenance_work_mem=32MB",
      "-c", "wal_level=minimal",
      "-c", "wal_level=replica",
      "-c", "max_wal_senders=0"
    ]
    mem_limit: 250m
    cpus: "0.5"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api:
    image: docker.io/juniorfredes/sicredi-api:0.1.1-alpine
    container_name: api-sicredi
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/votacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JAVA_TOOL_OPTIONS: >-
        -Xms128m -Xmx256m
        -XX:MaxMetaspaceSize=128m
        -Duser.timezone=UTC
    ports:
      - "8080:8080"
    mem_limit: 300m
    cpus: "0.8"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=12h"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
      - "--query.max-concurrency=4"
      - "--storage.tsdb.wal-compression"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    mem_limit: 400m
    cpus: "0.8"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    mem_limit: 250m
    cpus: "0.5"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - prometheus

volumes:
  pgdata_sicredi:
  grafana_storage:
  prometheus_data:
