name: Release (Build & Attach JAR)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build
        run: mvn -B -U clean package -DskipTests
      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp **/target/*.jar artifacts/ || true
      - uses: actions/upload-artifact@v4
        with:
          name: jars
          path: artifacts/*.jar

  attach:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: jars
          path: artifacts
      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
