name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

defaults:
  run:
    working-directory: sicredi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build & Test
        run: mvn -B -U clean verify
